"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
let age = 20;
console.log("is age==12? I predict true");
console.log(age == 12);
console.log("Is age less than 20? I predict true");
console.log(age < 20);
console.log("is age!=12? I predict false");
console.log(age != 12);
console.log("Is age greater than 20? I predict False");
console.log(age > 20);
let studname = 'Umar';
console.log("Is student name is Umar? I predict true");
console.log(studname == 'Umar');
console.log("Is student name not Haris? I predict true");
console.log(studname != 'Haris');
console.log("Is student name is not yasin? I predict False");
console.log(studname != 'yasin');
console.log("Is student name is Ali? I predict False");
console.log(studname == 'Ali');
